# Generated by Django 3.0.6 on 2020-07-11 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
